on:
  push:
    branches:
      - ch
    pull_request:
      branches:
        - ch

jobs: 
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Install Depedencies
          run: npm install

        - name: Run Linter
          run: npm run lint

        - name: Upload Coverage to Codecov
          uses: codecov/codecov-action@v4
          with:
            fail_ci_if_error: true
            files: ./coverage/*.json
            flags: unittests
            name: codecov-binar
            token: ${{ secrets.CODECOV_TOKEN }}
