on:
  push:
    branches:
      - ch
  pull_request:
    branches:
      - ch

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd ch_4
          npm install

      - name: Run Linter
        run: |
          cd ch_4
          npm run lint

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ch_4/coverage/lcov.info
          flags: unittests
          name: codecov-binar
          token: ${{ secrets.CODECOV_TOKEN }}