name: Deploy to Google App Engine (GAE)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd ch_4
          npm install --frozen-lockfile

      -- name: Set up Cloud SQL instance variable
        env:
          CLOUD_SQL_INSTANCE: ${{ secrets.CLOUD_SQL_INSTANCE }}
        run: |
          echo "beta_settings:" >> app.yaml
          echo "  cloud_sql_instances: '$CLOUD_SQL_INSTANCE'" >> app.yaml

      - name: Setup Environment
        run: |
          cd ch_4
          touch env.yaml
          echo "env_variables: " >> env.yaml
          echo "  DATABASE_URL: '${{ secrets.DATABASE_URL }}'" >> env.yaml
          echo "  SECRET_KEY: '${{ secrets.SECRET_KEY }}'" >> env.yaml
          echo "  IMAGEKIT_PUBLIC_KEY: '${{ secrets.IMAGEKIT_PUBLIC_KEY }}'" >> env.yaml
          echo "  IMAGEKIT_PRIVATE_KEY: '${{ secrets.IMAGEKIT_PRIVATE_KEY }}'" >> env.yaml
          echo "  IMAGEKIT_URL_ENDPOINT: '${{ secrets.IMAGEKIT_URL_ENDPOINT }}'" >> env.yaml

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Google App Engine
        run: |
          cd ch_4
          gcloud app deploy app.yaml --quiet
